global.centerCreep = require('centreCreep')
global.carryCreep = require('carryCreep')
global.upgradeCreep = require('upgradeCreep')
global.buildCreep = require('buildCreep')
global.harvestCreep = require('harvesteCreep')
global.terminalCreep = require('terminalCreep')
global.mineralCreep = require('mineralCreep')
global.mineralCarryCreep = require('mineralCarryCreep')
global.pc_operate = require('pc')
global.healCreep = require('healCreep')
global.upgrader_noob = require('upgrader_noob')
global.harvest_deposit = require('harvester_deposit')
global.builder_nood = require('builder_noob')
global.harvester_noob = require('harvester_noob')
global.tower = require('tower')

require('RoomVisual')
require('超级移动优化')